-- EX1: Average Population of Each Continent
SELECT T2.CONTINENT, FLOOR(AVG(T1.POPULATION))
FROM CITY AS T1
INNER JOIN COUNTRY AS T2
ON T1.COUNTRYCODE=T2.CODE
GROUP BY T2.CONTINENT
-- EX2: Signup Activation Rate [TikTok SQL Interview Question]
